### ISSUE TITLE
Sacar un release con el .apk

### ISSUE THREAD

**Issue by JJ** [elecciones-ugr/app#2]
Puedes crear un tag para hacer a partir de él un release. ¿Sabes como?

**Comment by iblancasa** [comment]
[Hecho](https://github.com/elecciones-ugr/app/releases/tag/0.1)

He rellenado como he pensado que estaría mejor, pero cambiad lo que veáis.

**Comment by Makova** [comment]
No se puede instalar como .apk Viendo a que es debido.

**Comment by iblancasa** [comment]
Qué raro. Yo lo he instalado en una tablet y en mi móvil. Si no funciona,
recompilaré a ver cuando llegue

**Comment by Makova** [comment]
Espera que me ha faltado compilarla. En cuanto la tenga compilada pruebo de nuevo.

**Comment by JJ** [comment]
Yo lo intenté ayer y tampoco me dejó... tuve que rebajar la seguridad,
incluso, pero ni así.

**Comment by Makova** [comment]
Ahora me faltaba nodejs-legacy en Ubuntu, sigo con ello.

**Comment by Makova** [comment]
Actualizando el sdk porque no hay manera, también es que llevo ya tiempo sin utilizarlo :smile_cat: 
![img_20150525_185437](https://cloud.githubusercontent.com/assets/3070918/7800083/2b562208-0310-11e5-9101-2ddac9bd74e1.jpg)

**Comment by Makova** [comment]
Y ¿no será mejor subir la apk ya compilada?.

**Comment by JJ** [comment]
Está en los releases.

2015-05-25 19:06 GMT+02:00 Manu <notifications@github.com>:

> Y ¿no será mejor subir la apk ya compilada?.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elecciones-ugr/app/issues/2#issuecomment-105271201>.
>



-- 
JJ

**Comment by Makova** [comment]
Si te refieres a la .apk que esta, esa es la que no me funciona.

**Comment by iblancasa** [comment]
¿Qué error os muestra?

**Comment by Makova** [comment]
Ya esta, la que acabo de compilar si me funciona en Lollipop 5.1.1 del OnePlus One.

**Comment by Makova** [comment]
¿Dónde la puedo subir?.

**Comment by iblancasa** [comment]
Puede que sea por eso (yo uso ese SDK)... Aunque debería funcionar, ya que
no hay cosas propias de esa versión del SDK (o lo mismo Cordova mete algo)

**Comment by Makova** [comment]
La acabo de subir, probar a ver.

**Comment by Makova** [comment]
Se instala sin problema, pero no va bien.

**Comment by iblancasa** [comment]
Pero, ¿qué falla?

**Comment by Makova** [comment]
Que no me van los enlaces de la osl ni sale el gráfico, entre otras.

**Comment by iblancasa** [comment]
Supongo que no has cambiado los permisos, así que eso no será.
Prueba a ejecutarlo desde el móvil pero en modo depuración a ver si funciona.
Para ejecutarlo con el modo depuración en la terminal hay que escribir ``cordova run android``

**Comment by Makova** [comment]
`debug:

BUILD SUCCESSFUL
Total time: 27 seconds
Built the following apk(s):
    /home/manu/app-0.1/platforms/android/ant-build/CordovaApp-debug.apk
WARNING : No started emulators found, starting an emulator.
Waiting for emulator...
Booting up emulator (this may take a while)...BOOT COMPLETE
WARNING : No target specified, deploying to emulator 'emulator-5554'.
Installing app on emulator...
Using apk: /home/manu/app-0.1/platforms/android/ant-build/CordovaApp-debug.apk
X Error of failed request:  BadAlloc (insufficient resources for operation)
  Major opcode of failed request:  149 ()
  Minor opcode of failed request:  2
  Serial number of failed request:  3080
  Current serial number in output stream:  3081`

**Comment by iblancasa** [comment]
Ni idea...
¿Podrías probar a ejecutarlo con el modo depuración pero en un teléfono? Ahí se está ejecutando con un emulador

**Comment by Makova** [comment]
Acabo de compilar otra y esta parece que va mejor. La subo como CordovaApp-debug.apk

**Comment by Makova** [comment]
Si que funciona con esta última.

**Comment by Makova** [comment]
Solo falla al descargar en json
![screenshot_2015-05-26-00-59-39](https://cloud.githubusercontent.com/assets/3070918/7802957/b4fc75de-0342-11e5-9a87-f08f9faf8a1f.png)

**Comment by iblancasa** [comment]
A mí no me ha dado error... pero una cosa si hay que tener en cuenta, que creo que no la habíamos visto hasta ahora: debería cargar el "resultados" del repo y está cargando el que se descarga, es decir, un fichero estático.

Lo que hay que hacer es cambiar, en el otro repo, el origen de los datos... Poniendo una URL

**Comment by iblancasa** [comment]
Hecho.
A ver si ahora da esos fallos

**Comment by JJ** [comment]
Gracias a los dos.

2015-05-26 1:18 GMT+02:00 Israel Blancas <notifications@github.com>:

> Hecho.
> A ver si ahora da esos fallos
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elecciones-ugr/app/issues/2#issuecomment-105333710>.
>



-- 
JJ

**Comment by iblancasa** [comment]
A mandar :D

**Comment by Makova** [comment]
Ya sabes que lo que haga falta @JJ 
Entonces, ahora solo descargo de nuevo el zip y vuelvo a compilarlo ¿no?.

**Comment by iblancasa** [comment]
¿El del código fuente? Se supone, ya que carga los datos de GitHub (el
enlace del archivo en RAW). A mí es que en ningún momento me dio fallo.

**Comment by Makova** [comment]
Sí, el código fuente. 
La apk que a ti te va bien sigue en el Release y a mi me peta, seguiré con la que subí yo que si me funciona. Me fije en la que subiste tú y le falta el META-INF con los CERT.RSA, CERT.SF y MANIFEST.MF. Solo lleva las carpetas assets y res, más los archivos AndroidManifest.xml classes.dex y resources.arsc

**Comment by iblancasa** [comment]
Lo del AndroidManifest me descoloca. En cuanto a los otros ficheros, ¿puede
que sea por que no lo he firmado?
No lo sé. He hecho costillas en Android pero nunca he subido nada al
market... Así que de la parte de publicación ando pegado. Puede que sea por
eso lo siento.

**Comment by Makova** [comment]
Ya he subido la nueva apk y en la que has solucionado lo de descargar en JSON. Buen trabajo Israel :+1:

**Comment by iblancasa** [comment]
Gracias, pero no hubiera funcionado sin tu ayuda @Makova 

¿Los ficheros esos que faltaban puede ser por que no la haya firmado? Es que como te digo no tengo muy claro cómo va para publicar una aplicación y puede que sea ahí donde la he piciado.... :worried:

**Comment by Makova** [comment]
Acabo de compilar con los cambios que ha añadido @JJ JJ en hooks y funciona bien. Ya no se cómo ni dónde comprobar nada en la apk.

**Comment by iblancasa** [comment]
Pues si todo funciona bien, ya lo que queda sería cambiar los datos del repo de GitHub y comprobar si se actualizan en la App

**Comment by JJ** [comment]
Pero mirad a ver si el hook funciona...

2015-05-26 23:36 GMT+02:00 Israel Blancas <notifications@github.com>:

> Pues si todo funciona bien, ya lo que queda sería cambiar los datos del
> repo de GitHub y comprobar si se actualizan en la App
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elecciones-ugr/app/issues/2#issuecomment-105671621>.
>



-- 
JJ

**Comment by iblancasa** [comment]
Pero ¿eso se ejecuta al lanzar Cordova o al compilarlo? Es que según leí
anoche era al compilar :S

**Comment by Makova** [comment]
Y compilar lo hizo sin problemas. Es la que tengo ahora instalada.

--
Makova

**Comment by iblancasa** [comment]
Por eso. Hay que cambiar el resultados y ver si se actualiza en el móvil
sin recompilar ni reinstalar la aplicación ni nada (eso significa que
estaría tomando los datos de la fuente correcta).

**Comment by JJ** [comment]
Se ejecuta cuando se compila, teóricamente. De todas formas si con eso se
compila y funciona, es que está bien, ¿no? Si tuviera el jsonp local no
funcionaría.

**Comment by iblancasa** [comment]
Claro.
Pero era para ver si se había ejecutado el hook. Lo digo por que vayamos a
que esté fallando algo y se sigan tomando los datos del local...

**Comment by JJ** [comment]
¿Y si se pone un "Esto se está ajecutando, la vín" a ver si ...?

El 27 de mayo de 2015, 8:16, Israel Blancas <notifications@github.com>
escribió:

> Claro.
> Pero era para ver si se había ejecutado el hook. Lo digo por que vayamos a
> que esté fallando algo y se sigan tomando los datos del local...
> El 27/5/2015 8:14, "Juan Julián Merelo Guervós" <notifications@github.com>
> escribió:
>
> > Se ejecuta cuando se compila, teóricamente. De todas formas si con eso se
> > compila y funciona, es que está bien, ¿no? Si tuviera el jsonp local no
> > funcionaría.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/elecciones-ugr/app/issues/2#issuecomment-105770945>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elecciones-ugr/app/issues/2#issuecomment-105771780>.
>



-- 
JJ

**Comment by Makova** [comment]
He cambiado el % a 40.96 de resultados. jsonp y no lo cambia en la apk.
Quizás hay que cambiarlo aquí también:

https://github.com/elecciones-ugr/elecciones-ugr.github.io/tree/a71765a6411f8548af07f4fb6c89641bf779327a

--
Makova

**Comment by iblancasa** [comment]
Si es que yo creo que sería lo más rápido y fácil. Por eso cambie el enlace
al raw e. Su momento. Ahora seria al de la página

**Comment by JJ** [comment]
Pero el hook lo que hace es cambiar el enlace a raw antes de compilarlo.

**Comment by iblancasa** [comment]
Comprendo. A mí con el RAW si me funcionaba... Y según dice Manuel también
va en la versión actual.

A lo que me refería era que, para comprobar que funciona, al cambiar algo
en el RAW, debe cambiar también en la app, sin cambiar la app

**Comment by iblancasa** [comment]
He ido a compilar y...

```bash
Running command: /home/iblancasa/Proyectos/appelecciones/hooks/before_build/01_change_jsonp.js /home/iblancasa/Proyectos/appelecciones

fs.js:432
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/home/iblancasa/Proyectos/appelecciones/config/project.json'
    at Object.fs.openSync (fs.js:432:18)
    at Object.fs.readFileSync (fs.js:286:15)
    at Object.<anonymous> (/home/iblancasa/Proyectos/appelecciones/hooks/before_build/01_change_jsonp.js:24:35)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
Error: Hook failed with error code 8: /home/iblancasa/Proyectos/appelecciones/hooks/before_build/01_change_jsonp.js
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:194:23
    at _rejected (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:797:24)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:823:30
    at Promise.when (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:741:41)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:415:13)

```

He borrado mi copia local, he clonado todo desde cero y otra vez el mismo fallo (y he comprobado los permisos)

**Comment by iblancasa** [comment]
Encima, creo que Git se está riendo de mí.
Clono el repo de la app usando ``git clone --recursive`` y miro el index.html... y me encuentro que no es la última versión (no es la que hay en GitHub) por que me falta esto
``<meta http-equiv="refresh" content="120">``

**Comment by iblancasa** [comment]
He hecho un pull y...

```bash
iblancasa@iblancasaPC:~/Proyectos/appelecciones/www$ git pull git@github.com:elecciones-ugr/elecciones-ugr.github.io.git
De github.com:elecciones-ugr/elecciones-ugr.github.io
 * branch            HEAD       -> FETCH_HEAD
Updating a71765a..3f22697
Fast-forward
 css/elecciones.css |   3 +++
 img/logoalter3.jpg | Bin 0 -> 25766 bytes
 index.html         |   7 ++++++-
 js/charts.js       |   5 ++++-
 resultados.jsonp   |   2 +-
 5 files changed, 14 insertions(+), 3 deletions(-)
 create mode 100644 css/elecciones.css
 create mode 100644 img/logoalter3.jpg

```

**Comment by JJ** [comment]
Es que como ahora hay un tag tienes que especificar la rama.

**Comment by iblancasa** [comment]
¿Al hacer el clone recursive le tengo que decir master o cómo?

He creado un fork para hacer un poco de guarreo, dirigiendo la app hacia una rama gh-pages de la web para que coja el JSONP de la web. Osea, lo que he propuesto por aquí, pero para no guarrear más el repo y ver que funciona.

**Comment by germaaan** [comment]
Estoy probando esto y la app me compila a la primera. Después he abierto el proyecto con el Android Studio para ver la depuración por consola y lo he ejecutado en el móvil. Cuando pulso algún botón de descargar los resultados me sale "D/CordovaWebViewImpl﹕ onPageFinished(file:///android_asset/www/resultados.csv)", por lo que está cogiendo bien el archivo de resultados del submodule.

¿Esos archivos se están actualizando automáticamente cuando se actualizan en el repo de "elecciones-ugr.github.io"?

**Comment by iblancasa** [comment]
@germaaan no. Hay que ponerlos con la URL de la web


Mirad:
* He eliminado el hook
* He cogido en mi gh-pages de la web y he puesto la dirección al jsonp, osea, para http://iblancasa.com/elecciones-ugr.github.io/ he hecho esto ``<script type="text/javascript" src='http://iblancasa.com/elecciones-ugr.github.io/resultados.jsonp'></script>``
* He cambiado el tiempo de refresco (para no esperar los dos minutos a ver si funcionaba)
* He compilado-firmado-instalado la aplicación (funcionando)
* Me he ido a mi JSONP (el de gh-pages) y he cambiado el nombre de uno de los candidatos por Pablo de Rojas
* Ha cambiado
* He vuelto a cambiarlo
* Ha cambiado

Pruebas
![screenshot_2015-05-27-10-44-43](https://cloud.githubusercontent.com/assets/4806311/7832292/2bf48d90-045e-11e5-8334-4b27489c168d.png)

![screenshot_2015-05-27-10-44-58](https://cloud.githubusercontent.com/assets/4806311/7832293/2f791134-045e-11e5-9e81-b4dbda489aa9.png)

**Comment by JJ** [comment]
Qué cracks.

El 27 de mayo de 2015, 10:50, Israel Blancas <notifications@github.com>
escribió:

> @germaaan <https://github.com/germaaan> no. Hay que ponerlos con la URL
> de la web
>
> Mirad:
>
>    - He eliminado el hook
>    - He cogido en mi gh-pages de la web y he puesto la dirección al
>    jsonp, osea, para http://iblancasa.com/elecciones-ugr.github.io/ he
>    hecho esto <script type="text/javascript" src='
>    http://iblancasa.com/elecciones-ugr.github.io/resultados.jsonp
>    '></script>
>    - He cambiado el tiempo de refresco (para no esperar los dos minutos a
>    ver si funcionaba)
>    - He compilado-firmado-instalado la aplicación (funcionando)
>    - Me he ido a mi JSONP (el de gh-pages) y he cambiado el nombre de uno
>    de los candidatos por Pablo de Rojas
>    - Ha cambiado
>    - He vuelto a cambiarlo
>    - Ha cambiado
>
> Pruebas
> [image: screenshot_2015-05-27-10-44-43]
> <https://cloud.githubusercontent.com/assets/4806311/7832292/2bf48d90-045e-11e5-8334-4b27489c168d.png>
>
> [image: screenshot_2015-05-27-10-44-58]
> <https://cloud.githubusercontent.com/assets/4806311/7832293/2f791134-045e-11e5-9e81-b4dbda489aa9.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elecciones-ugr/app/issues/2#issuecomment-105828318>.
>



-- 
JJ

**Comment by iblancasa** [comment]
¿Subo a algún lado la APK y si funciona me dejáis terminar de liar el
follón que tenemos? Jajaajajaj

**Comment by JJ** [comment]
Haz un release para que lo vayamos probando.

El 27 de mayo de 2015, 10:58, Israel Blancas <notifications@github.com>
escribió:

> ¿Subo a algún lado la APK y si funciona me dejáis terminar de liar el
> follón que tenemos? Jajaajajaj
> El 27/5/2015 10:57, "Juan Julián Merelo Guervós" <notifications@github.com
> >
> escribió:
>
> > Qué cracks.
> >
> > El 27 de mayo de 2015, 10:50, Israel Blancas <notifications@github.com>
> > escribió:
> >
> > > @germaaan <https://github.com/germaaan> no. Hay que ponerlos con la
> URL
> > > de la web
> > >
> > > Mirad:
> > >
> > > - He eliminado el hook
> > > - He cogido en mi gh-pages de la web y he puesto la dirección al
> > > jsonp, osea, para http://iblancasa.com/elecciones-ugr.github.io/ he
> > > hecho esto <script type="text/javascript" src='
> > > http://iblancasa.com/elecciones-ugr.github.io/resultados.jsonp
> > > '></script>
> > > - He cambiado el tiempo de refresco (para no esperar los dos minutos a
> > > ver si funcionaba)
> > > - He compilado-firmado-instalado la aplicación (funcionando)
> > > - Me he ido a mi JSONP (el de gh-pages) y he cambiado el nombre de uno
> > > de los candidatos por Pablo de Rojas
> > > - Ha cambiado
> > > - He vuelto a cambiarlo
> > > - Ha cambiado
> > >
> > > Pruebas
> > > [image: screenshot_2015-05-27-10-44-43]
> > > <
> >
> https://cloud.githubusercontent.com/assets/4806311/7832292/2bf48d90-045e-11e5-8334-4b27489c168d.png
> > >
> > >
> > > [image: screenshot_2015-05-27-10-44-58]
> > > <
> >
> https://cloud.githubusercontent.com/assets/4806311/7832293/2f791134-045e-11e5-9e81-b4dbda489aa9.png
> > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/elecciones-ugr/app/issues/2#issuecomment-105828318
> >.
> > >
> >
> >
> >
> > --
> > JJ
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/elecciones-ugr/app/issues/2#issuecomment-105829457>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elecciones-ugr/app/issues/2#issuecomment-105829816>.
>



-- 
JJ

**Comment by iblancasa** [comment]
Aquí tenéis. https://github.com/iblancasa/elecciones-ugr.github.io/releases/tag/0.0
La he colgado en mi fork por que bebe de los datos de ese repo.

**Comment by Makova** [comment]
Y cerramos este issue también.

**Comment by iblancasa** [comment]
Hola:

Israel te ha invitado a unirte a la Copa universitaria de Dropbox. La Copa universitaria te permite unirte a tus compañeros para conseguir hasta 25 GB de espacio de Dropbox gratis durante dos años.

Para conseguir espacio, solo tienes que invitar a amigos y utilizar Dropbox para compartir, colaborar y trabajar.

¡Únete a la Copa universitaria![2]

Ten en cuenta que, para participar, debes ser un alumno inscrito actualmente en un centro de enseñanza superior. Más información acerca de la Copa universitaria[3]

¡Disfruta de Dropbox!


 
 Trabaja en equipo, gana en equipo.

____________________________________________________
Si prefieres no recibir invitaciones de Dropbox, visita este enlace[4].
Dropbox, Inc., PO Box 77767, San Francisco, California 94107

[1]: https://www.dropbox.com/l/qQLSjUUiI35RSJING4cXpE/campuscup?text=1
[2]: https://www.dropbox.com/l/b9DKuC3funEjxMx5aE7PPo/campuscup?text=1
[3]: https://www.dropbox.com/l/JWEvopR9axCxRisJTq5L2h/help/9131?text=1
[4]: https://www.dropbox.com/l/wDuEBw07OQa5dgDrqR9TCw?text=1

**Comment by iblancasa** [comment]
Hola:

Israel te ha invitado a unirte a la Copa universitaria de Dropbox. La Copa universitaria te permite unirte a tus compañeros para conseguir hasta 25 GB de espacio de Dropbox gratis durante dos años.

Para conseguir espacio, solo tienes que invitar a amigos y utilizar Dropbox para compartir, colaborar y trabajar.

¡Únete a la Copa universitaria![2]

Ten en cuenta que, para participar, debes ser un alumno inscrito actualmente en un centro de enseñanza superior. Más información acerca de la Copa universitaria[3]

¡Disfruta de Dropbox!


 
 Trabaja en equipo, gana en equipo.

____________________________________________________
Si prefieres no recibir invitaciones de Dropbox, visita este enlace[4].
Dropbox, Inc., PO Box 77767, San Francisco, California 94107

[1]: https://www.dropbox.com/l/3orL0Fqo4NnkepqM9c3tEv/campuscup?text=1
[2]: https://www.dropbox.com/l/K0ELxI0UtEKyyVkqTY0pRn/campuscup?text=1
[3]: https://www.dropbox.com/l/4wt8PBerfH1NSrf4DLYk4g/help/9131?text=1
[4]: https://www.dropbox.com/l/P2xK0yct6gd6USv8qp5xrD?text=1

**Comment by iblancasa** [comment]
Hola:

Israel te ha invitado a unirte a la Copa universitaria de Dropbox. La Copa universitaria te permite unirte a tus compañeros para conseguir hasta 25 GB de espacio de Dropbox gratis durante dos años.

Para conseguir espacio, solo tienes que invitar a amigos y utilizar Dropbox para compartir, colaborar y trabajar.

¡Únete a la Copa universitaria![2]

Ten en cuenta que, para participar, debes ser un alumno inscrito actualmente en un centro de enseñanza superior. Más información acerca de la Copa universitaria[3]

¡Disfruta de Dropbox!


 
 Trabaja en equipo, gana en equipo.

____________________________________________________
Si prefieres no recibir invitaciones de Dropbox, visita este enlace[4].
Dropbox, Inc., PO Box 77767, San Francisco, California 94107

[1]: https://www.dropbox.com/l/VNPyX9OGJj1JLCVicGuwaw/campuscup?text=1
[2]: https://www.dropbox.com/l/8VlBZ24ixMoX59QWVsssno/campuscup?text=1
[3]: https://www.dropbox.com/l/iwWLRsftrxwbqFKAFfqoAg/help/9131?text=1
[4]: https://www.dropbox.com/l/A7TL6jVjzgIur61FsTwAXD?text=1

**Comment by iblancasa** [comment]
Hola:

Israel te ha invitado a unirte a la Copa universitaria de Dropbox. La Copa universitaria te permite unirte a tus compañeros para conseguir hasta 25 GB de espacio de Dropbox gratis durante dos años.

Para conseguir espacio, solo tienes que invitar a amigos y utilizar Dropbox para compartir, colaborar y trabajar.

¡Únete a la Copa universitaria![2]

Ten en cuenta que, para participar, debes ser un alumno inscrito actualmente en un centro de enseñanza superior. Más información acerca de la Copa universitaria[3]

¡Disfruta de Dropbox!


 
 Trabaja en equipo, gana en equipo.

____________________________________________________
Si prefieres no recibir invitaciones de Dropbox, visita este enlace[4].
Dropbox, Inc., PO Box 77767, San Francisco, California 94107

[1]: https://www.dropbox.com/l/9kWMEFiyCJ5tMIleIqSEYC/campuscup?text=1
[2]: https://www.dropbox.com/l/6lUrqZ7W4jhH6fgSrdQAbv/campuscup?text=1
[3]: https://www.dropbox.com/l/8HCtlcovRKBVqLawb0Owon/help/9131?text=1
[4]: https://www.dropbox.com/l/b0oSAu1rm5T9Lh5aVMLsBf?text=1

**Comment by iblancasa** [comment]
Hola:

Israel te ha invitado a unirte a la Copa universitaria de Dropbox. La Copa universitaria te permite unirte a tus compañeros para conseguir hasta 25 GB de espacio de Dropbox gratis durante dos años.

Para conseguir espacio, solo tienes que invitar a amigos y utilizar Dropbox para compartir, colaborar y trabajar.

¡Únete a la Copa universitaria![2]

Ten en cuenta que, para participar, debes ser un alumno inscrito actualmente en un centro de enseñanza superior. Más información acerca de la Copa universitaria[3]

¡Disfruta de Dropbox!


 
 Trabaja en equipo, gana en equipo.

____________________________________________________
Si prefieres no recibir invitaciones de Dropbox, visita este enlace[4].
Dropbox, Inc., PO Box 77767, San Francisco, California 94107

[1]: https://www.dropbox.com/l/oDyJCtSJlQY9OI1p4mfcMJ/campuscup?text=1
[2]: https://www.dropbox.com/l/Ezi9wHtQUt8o8fW2O8d8ZB/campuscup?text=1
[3]: https://www.dropbox.com/l/6IT4ABWcCyjCsLQGxVa4cu/help/9131?text=1
[4]: https://www.dropbox.com/l/sip4JE5eliNQMhLkhI80pm?text=1

**Comment by iblancasa** [comment]
Hola:

Israel te ha invitado a unirte a la Copa universitaria de Dropbox. La Copa universitaria te permite unirte a tus compañeros para conseguir hasta 25 GB de espacio de Dropbox gratis durante dos años.

Para conseguir espacio, solo tienes que invitar a amigos y utilizar Dropbox para compartir, colaborar y trabajar.

¡Únete a la Copa universitaria![2]

Ten en cuenta que, para participar, debes ser un alumno inscrito actualmente en un centro de enseñanza superior. Más información acerca de la Copa universitaria[3]

¡Disfruta de Dropbox!


 
 Trabaja en equipo, gana en equipo.

____________________________________________________
Si prefieres no recibir invitaciones de Dropbox, visita este enlace[4].
Dropbox, Inc., PO Box 77767, San Francisco, California 94107

[1]: https://www.dropbox.com/l/QmN8CTf2P3ALusqfZNpcbv/campuscup?text=1
[2]: https://www.dropbox.com/l/uMjGQzFrtwNZOYkTIAn8on/campuscup?text=1
[3]: https://www.dropbox.com/l/RSlXOLyXyxPd9vfxsnl4Bf/help/9131?text=1
[4]: https://www.dropbox.com/l/3nQQHcg5jkhxaWvBf1sgYC?text=1
